### ISSUE TITLE
Can't open settings page after installation

### ISSUE THREAD

**Issue by JanaSystopia** [systopia/de.systopia.civioffice#51] opened 2023-12-04 12:45 UTC
## Version

- CiviOffice: 1.0-beta2
- CiviCRM: 5.67.3
- Drupal: 10.1.6
- PHP: 8.1

## Problem

After installing CiviOffice I tried to open the settings page `civicrm/admin/civioffice/settings` but encountered the following error:
```
The website encountered an unexpected error. Please try again later.
```

In the Drupal Recent Log Messages Report I got the entry
```
TypeError: flock(): Argument #1 ($stream) must be of type resource, bool given in flock() (line 609 of /var/www/civicrm_env/funding/drupal/web/sites/default/files/civicrm/ext/de.systopia.civioffice/CRM/Civioffice/DocumentRendererType/LocalUnoconv.php).
```
This is the code that is referred to in the error: 
```php
    /**
     * wait for the unoconv resource to become available
     */
    protected function lock()
    {
        $lock_file_path = $this->unoconv_lock_file_path;
        if ($lock_file_path) {
            $this->unoconv_lock_file = fopen($lock_file_path, "r+");
            if (!flock($this->unoconv_lock_file, LOCK_EX)) {
                throw new Exception(E::ts("CiviOffice: Could not acquire unoconv lock."));
            }
        }
    }
```
## Work around

Debugging showed, that the variable `$this->unoconv_lock_file_path` was set to `/var/www/unoconv.lock`. I had initially created the file on another location. After moving the file to the location indicated, I could open the settings menue. There, I was able to configure the _Local Universal Office Converter (unoconv)_, set the path to the location I initally had planned and move the file there again. This solved the problem.

**Comment by jensschuppe** [comment] 2024-04-09 12:54
Duplicate of #48.

**Closed by jensschuppe** 2024-04-09 12:54 UTC
Labels: bug
